export const OTP_TTL_MS = 5 * 60 * 1000;
export const OTP_TTL_SECONDS = 300;
export const LOCK_DURATION_MS = 15 * 60 * 1000;
export const MAX_FAILED_ATTEMPTS = 5;
export const MAX_OTP_ATTEMPTS = 5;
export const REFRESH_TOKEN_TTL_MS = 7 * 24 * 60 * 60 * 1000;
export const OTP_LENGTH = 6;
export const BCRYPT_ROUNDS_PASSWORD = 12;
export const BCRYPT_ROUNDS_OTP = 10;
